-- The schema as it stood when it first got written down.
--
-- Generated from the JPA entity mappings, which were its only description until now: the app ran
-- with hibernate.ddl-auto=update, so tables appeared by inference at boot with nothing to review.
--
-- Runs on every boot (spring.sql.init), so everything here is idempotent. Constraints are dropped
-- and re-added rather than guarded by a DO block: Spring's script runner splits on ';' and does not
-- understand dollar-quoted bodies, so a DO block arrives at the server cut in half. Existing databases
-- already match it and every statement no-ops; a fresh database gets the schema. New changes go in
-- a numbered file beside this one and must be additive and idempotent too - there is no migration
-- tool tracking what has run.


    create table if not exists public.app_user (
        created_at timestamp(6) with time zone not null,
        class_group_id uuid,
        id uuid not null,
        organization_id uuid,
        display_name varchar(255) not null,
        login_id varchar(255) not null unique,
        password_hash varchar(255),
        role varchar(255) not null check (role in ('DIRECTOR','CLASS_ACCOUNT','PARENT')),
        primary key (id)
    );

    create table if not exists public.class_group (
        created_at timestamp(6) with time zone not null,
        id uuid not null,
        organization_id uuid not null,
        join_code varchar(255) not null unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table if not exists public.class_invite (
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        used_at timestamp(6) with time zone,
        class_group_id uuid not null,
        id uuid not null,
        token_hash varchar(255) not null unique,
        primary key (id)
    );

    create table if not exists public.organization (
        created_at timestamp(6) with time zone not null,
        subscription_updated_at timestamp(6) with time zone,
        id uuid not null,
        name varchar(255) not null,
        subscription_status varchar(255) not null check (subscription_status in ('NONE','TRIALING','ACTIVE','EXPIRED')),
        primary key (id)
    );

    create table if not exists public.route_prompt (
        id bigint generated by default as identity,
        instruction_text text not null,
        system_text text not null,
        version varchar(255) not null unique,
        primary key (id)
    );

    create table if not exists public.shadow_intent_candidates (
        distinct_session_count integer not null,
        occurrence_count integer not null,
        created_at timestamp(6) with time zone not null,
        first_seen_at timestamp(6) with time zone not null,
        last_seen_at timestamp(6) with time zone not null,
        reviewed_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        id uuid not null,
        representative_intent varchar(240) not null,
        review_note varchar(1000),
        anchor_id varchar(255) not null,
        intent_signature varchar(255) not null,
        review_status varchar(255) not null check (review_status in ('COLLECTING','READY_FOR_REVIEW','IN_REVIEW','APPROVED','REJECTED','PROMOTED')),
        story_id varchar(255) not null,
        primary key (id),
        unique (story_id, anchor_id, intent_signature)
    );

    create table if not exists public.shadow_question_observations (
        observed_at timestamp(6) with time zone not null,
        candidate_id uuid not null,
        event_id uuid not null unique,
        id uuid not null,
        session_id uuid not null,
        primary key (id)
    );

    create table if not exists public.story (
        requires_entitlement boolean not null default false not null,
        availability varchar(255) not null,
        cast_version varchar(255) not null,
        content_version varchar(255) not null,
        id varchar(255) not null,
        response_text_normalization_version varchar(255) not null,
        route_policy_version varchar(255) not null,
        route_prompt_version varchar(255) not null,
        slug varchar(255) not null unique,
        title varchar(255) not null,
        package_extras jsonb,
        primary key (id)
    );

    create table if not exists public.story_action_family (
        display_order integer not null,
        acknowledgement_text varchar(300) not null,
        meaning varchar(300) not null,
        report_summary varchar(300) not null,
        anchor_id varchar(255) not null,
        branch_asset_id varchar(255) not null,
        bridge_audio_id varchar(255) not null,
        id varchar(255) not null,
        rejoin_slot varchar(255),
        rejoin_target varchar(255),
        requires_family_id varchar(255),
        choice_copy_variants jsonb not null,
        requires_prior_family_ids jsonb not null,
        primary key (id)
    );

    create table if not exists public.story_anchor (
        concern_choice_response_text varchar(300),
        summary varchar(500) not null,
        default_fallback_family_id varchar(255) not null,
        default_rejoin_at varchar(255) not null,
        id varchar(255) not null,
        primary_speaker_id varchar(255) not null,
        scene_id varchar(255) not null,
        slot varchar(255) not null,
        story_id varchar(255) not null,
        allowed_speaker_ids jsonb not null,
        concern_choice_family_ids jsonb,
        forbidden_knowledge jsonb not null,
        stt_keywords jsonb not null,
        primary key (id)
    );

    create table if not exists public.story_asset (
        panel integer,
        id bigint generated by default as identity,
        category varchar(32) not null check (category in ('SCENE_ART','BRANCH_ART','NARRATION','BRIDGE')),
        family_id varchar(255),
        file varchar(255) not null,
        integrity varchar(255) not null,
        slug varchar(255) not null,
        story_id varchar(255) not null,
        primary key (id),
        unique (story_id, slug)
    );

    create table if not exists public.story_cast (
        id uuid not null,
        direction varchar(500) not null,
        profile varchar(500) not null,
        cast_tag varchar(255) not null,
        display_name varchar(255) not null,
        role varchar(255) not null,
        same_person_key varchar(255),
        speaker_id varchar(255) not null unique,
        story_id varchar(255) not null,
        voice varchar(255) not null,
        primary key (id),
        unique (story_id, cast_tag)
    );

    create table if not exists public.story_events (
        occurred_at timestamp(6) with time zone not null,
        received_at timestamp(6) with time zone not null,
        id uuid not null,
        session_id uuid not null,
        event_name varchar(255) not null check (event_name in ('LANDING_VIEW','LANDING_CTA_CLICK','STORY_STARTED','SCENE_REACHED','QUESTION_INVITE_SHOWN','QUESTION_SKIPPED','QUESTION_STARTED','CHOICE_SELECTED','QUESTION_RESULT','PLAYBACK_ISSUE','EXPLICIT_EXIT','STORY_COMPLETED','PARENT_REPORT_OPENED','SURVEY_OPENED')),
        source varchar(255) not null check (source in ('LANDING','PLAYER')),
        metadata jsonb not null,
        primary key (id)
    );

    create table if not exists public.story_fallback_segment (
        display_order integer not null,
        is_branch_point boolean not null,
        id uuid not null,
        family_id varchar(255) not null,
        kind varchar(255) not null,
        payload jsonb not null,
        primary key (id)
    );

    create table if not exists public.story_scene (
        sequence integer not null,
        checkpoint_id varchar(255) not null,
        id varchar(255) not null,
        story_id varchar(255) not null,
        title varchar(255) not null,
        primary key (id)
    );

    create table if not exists public.story_segment (
        display_order integer not null,
        is_branch_point boolean not null,
        id uuid not null,
        kind varchar(255) not null,
        scene_id varchar(255) not null,
        payload jsonb not null,
        primary key (id)
    );

    create table if not exists public.story_sessions (
        completed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        first_landing_at timestamp(6) with time zone,
        last_seen_at timestamp(6) with time zone not null,
        player_started_at timestamp(6) with time zone,
        survey_opened_at timestamp(6) with time zone,
        id uuid not null,
        entry_source varchar(255) not null check (entry_source in ('LANDING','PLAYER','DIRECT')),
        landing_release varchar(255),
        story_id varchar(255) not null,
        traffic_type varchar(255) not null,
        utm_campaign varchar(255),
        utm_content varchar(255),
        utm_medium varchar(255),
        utm_source varchar(255),
        primary key (id)
    );

    create table if not exists public.voice_research_consents (
        consented_at timestamp(6) with time zone not null,
        created_at timestamp(6) with time zone not null,
        expires_at timestamp(6) with time zone not null,
        id uuid not null,
        consent_method varchar(255) not null,
        consent_version varchar(255) not null,
        deletion_token_hash varchar(255) not null unique,
        primary key (id)
    );

    create table if not exists public.voice_research_samples (
        byte_size integer not null,
        duration_millis integer not null,
        question_round integer not null,
        created_at timestamp(6) with time zone not null,
        outcome_recorded_at timestamp(6) with time zone,
        consent_id uuid not null,
        id uuid not null,
        confirmed_transcript varchar(240) not null,
        intent_summary varchar(240),
        stt_draft varchar(240) not null,
        anchor_id varchar(255) not null,
        coverage_status varchar(255) check (coverage_status in ('EXACT','PARTIAL','UNCOVERED')),
        mime_type varchar(255) not null,
        routed_family_id varchar(255),
        scene_id varchar(255) not null,
        storage_object_name varchar(255) not null unique,
        story_id varchar(255) not null,
        primary key (id)
    );

    create index if not exists story_events_session_received_idx 
       on public.story_events (session_id, received_at);

    create index if not exists story_events_name_received_idx 
       on public.story_events (event_name, received_at);
alter table if exists public.app_user drop constraint if exists FKiuq58qela6u2kp5wdichxalt7;
    alter table if exists public.app_user 
       add constraint FKiuq58qela6u2kp5wdichxalt7 
       foreign key (class_group_id) 
       references public.class_group;
alter table if exists public.app_user drop constraint if exists FKfl8n74ioc02b9cpjqdlpi0m9f;
    alter table if exists public.app_user 
       add constraint FKfl8n74ioc02b9cpjqdlpi0m9f 
       foreign key (organization_id) 
       references public.organization;
alter table if exists public.class_group drop constraint if exists FK43591w82jxjyci6b39c3qo3at;
    alter table if exists public.class_group 
       add constraint FK43591w82jxjyci6b39c3qo3at 
       foreign key (organization_id) 
       references public.organization 
       on delete cascade;
alter table if exists public.class_invite drop constraint if exists FKoshm7m4ejveu4kwadyvm8ml6q;
    alter table if exists public.class_invite 
       add constraint FKoshm7m4ejveu4kwadyvm8ml6q 
       foreign key (class_group_id) 
       references public.class_group 
       on delete cascade;
alter table if exists public.shadow_question_observations drop constraint if exists FKa5qwa8dfdqo4sv3di8wsb56jg;
    alter table if exists public.shadow_question_observations 
       add constraint FKa5qwa8dfdqo4sv3di8wsb56jg 
       foreign key (candidate_id) 
       references public.shadow_intent_candidates 
       on delete cascade;
alter table if exists public.shadow_question_observations drop constraint if exists FKc4huh0pjvmm6oyxqswqy3ufwg;
    alter table if exists public.shadow_question_observations 
       add constraint FKc4huh0pjvmm6oyxqswqy3ufwg 
       foreign key (event_id) 
       references public.story_events 
       on delete cascade;
alter table if exists public.shadow_question_observations drop constraint if exists FK4xaiy00hv882vbh7txswr4pny;
    alter table if exists public.shadow_question_observations 
       add constraint FK4xaiy00hv882vbh7txswr4pny 
       foreign key (session_id) 
       references public.story_sessions;
alter table if exists public.story_action_family drop constraint if exists FKq5rjiwpa5wt85saryg9e547rg;
    alter table if exists public.story_action_family 
       add constraint FKq5rjiwpa5wt85saryg9e547rg 
       foreign key (anchor_id) 
       references public.story_anchor 
       on delete cascade;
alter table if exists public.story_anchor drop constraint if exists FKohsq166ie94pmd12ohcklb0ge;
    alter table if exists public.story_anchor 
       add constraint FKohsq166ie94pmd12ohcklb0ge 
       foreign key (story_id) 
       references public.story 
       on delete cascade;
alter table if exists public.story_asset drop constraint if exists FKpascuvx1gkgix5qu8d647yru4;
    alter table if exists public.story_asset 
       add constraint FKpascuvx1gkgix5qu8d647yru4 
       foreign key (story_id) 
       references public.story 
       on delete cascade;
alter table if exists public.story_cast drop constraint if exists FK7m4yi7n99vys7i6j0iu9wwo8u;
    alter table if exists public.story_cast 
       add constraint FK7m4yi7n99vys7i6j0iu9wwo8u 
       foreign key (story_id) 
       references public.story 
       on delete cascade;
alter table if exists public.story_events drop constraint if exists FKm6ped8qpkc8id7v0qveki9auo;
    alter table if exists public.story_events 
       add constraint FKm6ped8qpkc8id7v0qveki9auo 
       foreign key (session_id) 
       references public.story_sessions 
       on delete cascade;
alter table if exists public.story_fallback_segment drop constraint if exists FKcgmsu00655fh3yi6hce8fe8xs;
    alter table if exists public.story_fallback_segment 
       add constraint FKcgmsu00655fh3yi6hce8fe8xs 
       foreign key (family_id) 
       references public.story_action_family 
       on delete cascade;
alter table if exists public.story_scene drop constraint if exists FKohxnjy1llo26rwv375a6lao9p;
    alter table if exists public.story_scene 
       add constraint FKohxnjy1llo26rwv375a6lao9p 
       foreign key (story_id) 
       references public.story 
       on delete cascade;
alter table if exists public.story_segment drop constraint if exists FK40h7vvo03j98qoaeuvdhqntel;
    alter table if exists public.story_segment 
       add constraint FK40h7vvo03j98qoaeuvdhqntel 
       foreign key (scene_id) 
       references public.story_scene 
       on delete cascade;
alter table if exists public.voice_research_samples drop constraint if exists FKb7yu2mncdxayy2jujd9cefw08;
    alter table if exists public.voice_research_samples 
       add constraint FKb7yu2mncdxayy2jujd9cefw08 
       foreign key (consent_id) 
       references public.voice_research_consents 
       on delete cascade;
