-- Editing history for story content.
--
-- Content is moving out of the fe/content/*.qstory|yaml files and into this database. Those files
-- had one property this schema has to replace deliberately rather than lose: git. Every edit was
-- reviewable, attributable, and revertible. A row that is simply UPDATEd in place has none of that.
--
-- So every authoring write appends a revision here first, carrying the full prior state of what it
-- touched. Reverting is replaying an older snapshot; auditing is reading the table in order.

create table if not exists public.story_revision (
    id bigint generated by default as identity,
    story_id varchar(255) not null,
    -- Monotonic per story, assigned by the service under the story's row lock.
    revision integer not null,
    -- Which kind of thing changed: SCENE, SEGMENT, ANCHOR, ACTION_FAMILY, ASSET, CAST, PROMPT.
    target_type varchar(32) not null,
    -- Primary key of the changed row, as text so one column serves uuid/varchar/bigint targets.
    target_id varchar(255) not null,
    operation varchar(16) not null,
    -- The target's full state before this edit; null for CREATE.
    before_state jsonb,
    -- The target's full state after this edit; null for DELETE.
    after_state jsonb,
    -- app_user.id of the editor. Null for the content:import pipeline, which acts as the system.
    author_id uuid,
    summary varchar(500),
    created_at timestamp(6) with time zone not null,
    primary key (id)
);
alter table if exists public.story_revision drop constraint if exists fk_story_revision_story;
    alter table if exists public.story_revision
    add constraint fk_story_revision_story
    foreign key (story_id) references public.story on delete cascade;
alter table if exists public.story_revision drop constraint if exists fk_story_revision_author;
    alter table if exists public.story_revision
    add constraint fk_story_revision_author
    foreign key (author_id) references public.app_user on delete set null;

-- One revision number per story, which is also what makes a concurrent edit fail loudly instead of
-- interleaving two authors' writes.
alter table if exists public.story_revision drop constraint if exists uk_story_revision_story_revision;
    alter table if exists public.story_revision
    add constraint uk_story_revision_story_revision unique (story_id, revision);

-- The history view is always "this story, newest first".
create index if not exists idx_story_revision_story_created
    on public.story_revision (story_id, revision desc);

-- "What happened to this scene?" without scanning a story's whole history.
create index if not exists idx_story_revision_target
    on public.story_revision (story_id, target_type, target_id);
